name: CI
on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Integration test
        id: selftest
        # Put your action repo here
        uses: eliarms/download-release-assets@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.result }}" == "success"
        shell: bash

  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - name: Install Dependencies
        run: npm ci
        env:
          CI: true

      - name: ZIP Assets    
        run: zip -r gh-download-release.zip ./ -x "/*node_modules/*" 

      - name: Create a release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
