name: CI
on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: eliarms/download-release-assets@main

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.result }}" == "Hello world"
        shell: bash

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - name: Install Dependencies
        run: npm ci
        env:
          CI: true

      - name: ZIP Assets
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: zip -r gh-download-release.zip ./ -x "/*node_modules/*" 

      - name: Create a release
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
