name: CI
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*.*.* # skip semantic-release tags
  pull_request:

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Integration test
        id: selftest
        # Put your action repo here
        uses: eliarms/download-release-assets@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.result }}" == "success"
        shell: bash

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Create a release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
